### ISSUE TITLE
Doesn't build on kernel 6.15

### ISSUE THREAD

**Issue by F-Poole** [fofajardo/rtl8851bu#9]
On Archlinux, the output of make is:
> make -C /lib/modules/6.15.4-arch2-1/build M=/var/lib/dkms/rtl8851bu/1.19.10.r28.19802fa/build  modules
make[1]: Entering directory '/usr/lib/modules/6.15.4-arch2-1/build'
make[2]: Entering directory '/var/lib/dkms/rtl8851bu/1.19.10.r28.19802fa/build'
  CC [M]  platform/platform_ops.o
platform/platform_ops.c:15:10: fatal error: drv_types.h: No such file or directory
   15 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/lib/modules/6.15.4-arch2-1/build/scripts/Makefile.build:203: platform/platform_ops.o] Error 1
make[3]: *** [/usr/lib/modules/6.15.4-arch2-1/build/Makefile:2003: .] Error 2
make[2]: *** [/usr/lib/modules/6.15.4-arch2-1/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/rtl8851bu/1.19.10.r28.19802fa/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.15.4-arch2-1/build'
make: *** [Makefile:825: modules] Error 2

**Comment by fofajardo** [comment]
Will get this fixed soon. Apparently `EXTRA_CFLAGS`, which was previously deprecated, is now ignored by the kernel build system...

**Comment by fofajardo** [comment]
This should be resolved by https://github.com/fofajardo/rtl8851bu/commit/74bc28dbd48470aaa44bf6ee2f874d61f39b9c36. Let me know if it doesn't fix it for you. Thanks!
